version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_manager_tool:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: manager-tool
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password

volumes:
  mysql_manager_tool: {}
